[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "resolve-time"
version = "0.0.1"
dependencies = [
  "typer",
  "requests",
  "numpy",
  "pandas",
]

[project.scripts]
greet = "greetings.cli:app"
